FROM "nvcr.io/nvidia/l4t-ml:r32.4.3-py3"
LABEL maintainer="M. Edward (Ed) Borasky <znmeb@znmeb.net>"

ENV R_SOURCE_TARBALL="https://cloud.r-project.org/src/base/R-4/R-4.0.2.tar.gz"
ENV RSTUDIO_VERSION_MAJOR=1
ENV RSTUDIO_VERSION_MINOR=3
ENV RSTUDIO_VERSION_PATCH=1056
ENV SOURCE_DIR=/usr/local/src
ENV EDGYR_HOME=/home/edgyr
ENV PAPERSIZE=letter
ENV PROJECT_HOME=$EDGYR_HOME/Projects
ENV WORKON_HOME=$EDGYR_HOME/.virtualenvs
ENV EDGYR_LOGFILES=$EDGYR_HOME/logfiles

ARG DEBIAN_FRONTEND=noninteractive

# image building
USER root
WORKDIR $SOURCE_DIR/

# install linux dependencies
COPY install-linux-dependencies install-julia install-site-packages $SOURCE_DIR/
RUN $SOURCE_DIR/install-linux-dependencies > install-linux-dependencies.log 2>&1 \
  && gzip -9 install-linux-dependencies.log
RUN $SOURCE_DIR/install-site-packages > install-site-packages.log 2>&1 \
  && gzip -9 install-site-packages.log
RUN $SOURCE_DIR/install-julia > install-julia.log 2>&1 \
  && gzip -9 install-julia.log

RUN locale-gen en_US.UTF-8 \
  && update-locale \
    LANG=en_US.UTF-8 \
    LC_CTYPE=en_US.UTF-8 \
    LC_NUMERIC=en_US.UTF-8 \
    LC_TIME=en_US.UTF-8 \
    LC_COLLATE=en_US.UTF-8 \
    LC_MONETARY=en_US.UTF-8 \
    LC_MESSAGES=en_US.UTF-8 \
    LC_PAPER=en_US.UTF-8 \
    LC_NAME=en_US.UTF-8 \
    LC_ADDRESS=en_US.UTF-8 \
    LC_TELEPHONE=en_US.UTF-8 \
    LC_MEASUREMENT=en_US.UTF-8 \
    LC_IDENTIFICATION=en_US.UTF-8 \
  && cat /etc/default/locale
