FROM edgyr-ml
LABEL maintainer="M. Edward (Ed) Borasky <znmeb@znmeb.net>"

ENV R_SOURCE_TARBALL="https://cloud.r-project.org/src/base/R-4/R-4.0.2.tar.gz"
ENV RSTUDIO_VERSION_MAJOR=1
ENV RSTUDIO_VERSION_MINOR=3
ENV RSTUDIO_VERSION_PATCH=1056
ENV SOURCE_DIR=/usr/local/src
ENV EDGYR_HOME=/home/edgyr
ENV PAPERSIZE=letter
ENV PROJECT_HOME=$EDGYR_HOME/Projects
ENV WORKON_HOME=$EDGYR_HOME/.virtualenvs
ENV EDGYR_LOGFILES=$EDGYR_HOME/Logfiles

ARG DEBIAN_FRONTEND=noninteractive

# switch to 'edgyr' account to install 'tensorflow-2' virtual environment
# and R library packages
USER edgyr
WORKDIR $EDGYR_HOME
RUN installers/python-tensorflow-2 > $EDGYR_LOGFILES/python-tensorflow-2.log 2>&1 \
  && gzip -9 $EDGYR_LOGFILES/python-tensorflow-2.log

# switch back to 'root'
USER root
WORKDIR $SOURCE_DIR
