FROM base
LABEL maintainer="M. Edward (Ed) Borasky <znmeb@znmeb.net>"

ARG DEBIAN_INTERACTIVE
ARG PACKAGE_FILE
ARG R_PACKAGE_REPO
ARG SOURCE_DIR

USER root
WORKDIR $SOURCE_DIR

# copy RStudio Server package from binaries image
COPY --from=binaries $R_PACKAGE_REPO/$PACKAGE_FILE $R_PACKAGE_REPO/

# install it
RUN apt-get install -qqy --no-install-recommends \
    $R_PACKAGE_REPO/$PACKAGE_FILE \
  && apt-get autoremove --purge \
  && apt-get clean

# see https://support.rstudio.com/hc/en-us/articles/200552306-Getting-Started
COPY rstudio-configure $SOURCE_DIR/
COPY rserver.conf /etc/rstudio/
RUN $SOURCE_DIR/rstudio-configure

# set entry point
COPY docker-entrypoint.sh /
CMD [ "/docker-entrypoint.sh" ]
