FROM base
LABEL maintainer="M. Edward (Ed) Borasky <znmeb@znmeb.net>"

ENV R_SOURCE_TARBALL="https://cloud.r-project.org/src/base/R-4/R-4.0.2.tar.gz"
ENV RSTUDIO_VERSION_MAJOR=1
ENV RSTUDIO_VERSION_MINOR=3
ENV RSTUDIO_VERSION_PATCH=959
ENV SOURCE_DIR=/usr/local/src
ENV EDGYR_HOME=/home/edgyr
ENV PAPERSIZE=letter
ENV PROJECT_HOME=$EDGYR_HOME/Projects
ENV WORKON_HOME=$EDGYR_HOME/.virtualenvs

ARG DEBIAN_FRONTEND=noninteractive

# copy R files from binaries image
COPY --from=binaries /usr/local/lib/R /usr/local/lib/R
COPY --from=binaries /usr/local/share/man/man1 /usr/local/share/man/man1
COPY --from=binaries /usr/local/bin /usr/local/bin
COPY --from=binaries /usr/local/lib/pkgconfig /usr/local/lib/pkgconfig
COPY R.conf ld.so.conf.d/
RUN /sbin/ldconfig

# copy RStudio Server files from binaries image
COPY --from=binaries /usr/local/lib/rstudio-server /usr/local/lib/rstudio-server

# fetch build logs from binaries image
COPY --from=binaries \
  /usr/local/src/install-r.log.gz \
  /usr/local/src/install-rstudio-server.log.gz \
  /usr/local/src/

# configure RStudio Server
# see https://support.rstudio.com/hc/en-us/articles/200552306-Getting-Started
COPY rstudio-configure $SOURCE_DIR/
COPY rserver.conf /etc/rstudio/
RUN $SOURCE_DIR/rstudio-configure

# create non-root user with 'sudo' privilege
RUN useradd \
  --shell /bin/bash \
  --user-group \
  --groups sudo \
  --create-home \
  --uid 1000 edgyr \
  && echo "edgyr:edgyr" | chpasswd

# populate 'edgyr' home
COPY --chown=edgyr:edgyr bash_aliases $EDGYR_HOME/.bash_aliases
COPY --chown=edgyr:edgyr Rprofile $EDGYR_HOME/.Rprofile
COPY --chown=edgyr:edgyr Renviron $EDGYR_HOME/.Renviron
COPY --chown=edgyr:edgyr Installers $EDGYR_HOME/Installers
RUN mkdir --parents $WORKON_HOME $PROJECT_HOME; chown -R edgyr:edgyr $EDGYR_HOME

# shift to 'edgyr' account to install 'r-reticulate' virtual environment
# and R developer tools
USER edgyr
WORKDIR $EDGYR_HOME
RUN Installers/python-venv > Installers/python-venv.log 2>&1 \
  && gzip -9 Installers/python-venv.log
RUN Installers/devtools.R > Installers/devtools.R.log 2>&1 \
  && gzip -9 Installers/devtools.R.log

# switch back to 'root' for the rest
USER root
WORKDIR $SOURCE_DIR

# copy scripts
COPY --chown=edgyr:edgyr Scripts $EDGYR_HOME/Scripts

# set entry point
COPY docker-entrypoint.sh /
CMD [ "/docker-entrypoint.sh" ]
