FROM r-package-repo
LABEL maintainer="M. Edward (Ed) Borasky <znmeb@znmeb.net>"

# prep RStudio Server - mostly download time and building boost
# see https://rstudio.com/products/rstudio/download-server/other-platforms/
ARG DEBIAN_FRONTEND
ARG RSTUDIO_VERSION_MAJOR
ARG RSTUDIO_VERSION_MINOR
ARG RSTUDIO_VERSION_PATCH
ARG SOURCE_DIR
 
USER root
WORKDIR $SOURCE_DIR

COPY prep-rstudio-server $SOURCE_DIR/
RUN $SOURCE_DIR/prep-rstudio-server > prep-rstudio-server.log 2>&1
