FROM base
LABEL maintainer="M. Edward (Ed) Borasky <znmeb@znmeb.net>"

# prep RStudio Server - mostly download time and building boost
# see https://rstudio.com/products/rstudio/download-server/other-platforms/
ARG SOURCE_DIR
ARG RSTUDIO_VERSION_MAJOR
ARG RSTUDIO_VERSION_MINOR
ARG RSTUDIO_VERSION_PATCH
ARG EDGYR_LOGFILES
 
USER root
WORKDIR $SOURCE_DIR

COPY prep-rstudio-server $SOURCE_DIR/
RUN $SOURCE_DIR/prep-rstudio-server > $EDGYR_LOGFILES/prep-rstudio-server.log 2>&1 \
  && gzip -9 $EDGYR_LOGFILES/prep-rstudio-server.log
