FROM "nvcr.io/nvidia/l4t-ml:r32.4.3-py3"
LABEL maintainer="M. Edward (Ed) Borasky <znmeb@znmeb.net>"

# create non-root user with 'sudo' privilege
RUN useradd \
  --shell /bin/bash \
  --user-group \
  --groups sudo \
  --create-home \
  --uid 1000 edgyr \
  && echo "edgyr:edgyr" | chpasswd

# create 'edgyr' home directories
ARG EDGYR_HOME
ARG EDGYR_LOGFILES
ARG PROJECT_HOME
ARG WORKON_HOME
ENV PROJECT_HOME=$PROJECT_HOME
ENV WORKON_HOME=$WORKON_HOME
RUN mkdir --parents $EDGYR_LOGFILES $PROJECT_HOME $WORKON_HOME

USER root
ARG SOURCE_DIR
WORKDIR $SOURCE_DIR/
ARG DEBIAN_FRONTEND

# get the package repository
ARG R_PACKAGE_REPO
COPY --from=r-package-repo $R_PACKAGE_REPO $R_PACKAGE_REPO

# install linux dependencies
COPY install-linux-dependencies install-julia install-site-packages install-repo-packages $SOURCE_DIR/
RUN $SOURCE_DIR/install-linux-dependencies > $EDGYR_LOGFILES/install-linux-dependencies.log 2>&1 \
  && gzip -9 $EDGYR_LOGFILES/install-linux-dependencies.log

# install Python site-packages
RUN $SOURCE_DIR/install-site-packages > $EDGYR_LOGFILES/install-site-packages.log 2>&1 \
  && gzip -9 $EDGYR_LOGFILES/install-site-packages.log

# install Julia
ARG JULIA_TARBALL
RUN $SOURCE_DIR/install-julia > $EDGYR_LOGFILES/install-julia.log 2>&1 \
  && gzip -9 $EDGYR_LOGFILES/install-julia.log

# install R and recommended packages
RUN $SOURCE_DIR/install-repo-packages > $EDGYR_LOGFILES/install-repo-packages.log 2>&1 \
  && gzip -9 $EDGYR_LOGFILES/install-repo-packages.log

RUN locale-gen en_US.UTF-8 \
  && update-locale \
    LANG=en_US.UTF-8 \
    LC_CTYPE=en_US.UTF-8 \
    LC_NUMERIC=en_US.UTF-8 \
    LC_TIME=en_US.UTF-8 \
    LC_COLLATE=en_US.UTF-8 \
    LC_MONETARY=en_US.UTF-8 \
    LC_MESSAGES=en_US.UTF-8 \
    LC_PAPER=en_US.UTF-8 \
    LC_NAME=en_US.UTF-8 \
    LC_ADDRESS=en_US.UTF-8 \
    LC_TELEPHONE=en_US.UTF-8 \
    LC_MEASUREMENT=en_US.UTF-8 \
    LC_IDENTIFICATION=en_US.UTF-8 \
  && cat /etc/default/locale

# reconfigure R Java interface
RUN R CMD javareconf > $SOURCE_DIR/r-java-reconf.log 2>&1 \
  && gzip -9 $SOURCE_DIR/r-java-reconf.log

# populate 'edgyr' home
COPY --chown=edgyr:edgyr bash_aliases $EDGYR_HOME/.bash_aliases
COPY --chown=edgyr:edgyr Rprofile $EDGYR_HOME/.Rprofile
COPY --chown=edgyr:edgyr Renviron $EDGYR_HOME/.Renviron
COPY --chown=edgyr:edgyr \
  base-linux-packages \
  base-r-packages.R \
  edit-me-then-run-4-git-config.bash \
  start-jupyter-lab \
  $EDGYR_HOME/

# install dependencies for R packages
RUN $EDGYR_HOME/base-linux-packages > $EDGYR_LOGFILES/base-linux-packages.log 2>&1 \
  && gzip -9 $EDGYR_LOGFILES/base-linux-packages.log

# switch to non-root user
RUN chown -R edgyr:edgyr $EDGYR_HOME
USER edgyr
WORKDIR $EDGYR_HOME
CMD /bin/bash

# enable Julia kernel
RUN JUPYTER=/usr/local/bin/jupyter julia -e 'using Pkg; Pkg.add("IJulia"); Pkg.add("CUDA")' \
  > $EDGYR_LOGFILES/julia-kernel.log 2>&1 \
  && gzip -9 $EDGYR_LOGFILES/julia-kernel.log

# install base R packages
RUN $EDGYR_HOME/base-r-packages.R > $EDGYR_LOGFILES/base-r-packages.R.log 2>&1 \
  && gzip -9 $EDGYR_LOGFILES/base-r-packages.R.log

# copy installers and test scripts at the end
COPY --chown=edgyr:edgyr installers $EDGYR_HOME/installers
COPY --chown=edgyr:edgyr test-scripts $EDGYR_HOME/test-scripts

# set entry point
CMD [ "/bin/bash" ]
