FROM rsprep
LABEL maintainer="M. Edward (Ed) Borasky <znmeb@znmeb.net>"

# install RStudio Server
# see https://rstudio.com/products/rstudio/download-server/other-platforms/
COPY install-rstudio-server $SOURCE_DIR/
RUN $SOURCE_DIR/install-rstudio-server > install-rstudio-server.log 2>&1 \
  && gzip -9 install-rstudio-server.log
