FROM rsprep
LABEL maintainer="M. Edward (Ed) Borasky <znmeb@znmeb.net>"

ENV R_SOURCE_TARBALL="https://cloud.r-project.org/src/base/R-4/R-4.0.2.tar.gz"
ENV RSTUDIO_VERSION_MAJOR=1
ENV RSTUDIO_VERSION_MINOR=3
ENV RSTUDIO_VERSION_PATCH=1056
ENV SOURCE_DIR=/usr/local/src
ENV EDGYR_HOME=/home/edgyr
ENV PAPERSIZE=letter
ENV PROJECT_HOME=$EDGYR_HOME/Projects
ENV WORKON_HOME=$EDGYR_HOME/.virtualenvs
ENV EDGYR_LOGFILES=$EDGYR_HOME/logfiles

ARG DEBIAN_FRONTEND=noninteractive

# install RStudio Server
# see https://rstudio.com/products/rstudio/download-server/other-platforms/
COPY install-rstudio-server $SOURCE_DIR/
RUN $SOURCE_DIR/install-rstudio-server > install-rstudio-server.log 2>&1 \
  && gzip -9 install-rstudio-server.log
