FROM "nvcr.io/nvidia/l4t-ml:r32.4.3-py3"
LABEL maintainer="M. Edward (Ed) Borasky <znmeb@znmeb.net>"

# Apt operations
ARG DEBIAN_FRONTEND
ARG R_PACKAGE_REPO
ARG SOURCE_DIR

USER root
WORKDIR $SOURCE_DIR

RUN apt-get update \
  && apt-get upgrade -y \
  && apt-get install -qqy --no-install-recommends \
    gnupg \
  && apt-get autoremove --purge \
  && apt-get clean
    #ca-certificates \
    #build-essential \
    #dpkg-dev \
    #fakeroot \

# allow fetching sources and add R Ubuntu repository
COPY sources.list.new /etc/apt/sources.list

# build and install r-base packages
RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E298A3A825C0D65DFD57CBB651716619E084DAB9
RUN apt-get update

# make and install the packages
COPY compile-r-base compile-r-recommended $SOURCE_DIR/
RUN $SOURCE_DIR/compile-r-base
RUN $SOURCE_DIR/compile-r-recommended

# collect the packages into a repository
RUN mkdir --parents $R_PACKAGE_REPO \
  && cp r-*/*.deb $R_PACKAGE_REPO
