FROM rsprep
LABEL maintainer="M. Edward (Ed) Borasky <znmeb@znmeb.net>"

ARG PACKAGE_FILE
ARG R_PACKAGE_REPO
ARG RSTUDIO_VERSION_MAJOR
ARG RSTUDIO_VERSION_MINOR
ARG RSTUDIO_VERSION_PATCH
ARG SOURCE_DIR

ARG BUILD_DIR=$SOURCE_DIR/rstudio/build

USER root
WORKDIR $SOURCE_DIR

# package RStudio Server
# see https://rstudio.com/products/rstudio/download-server/other-platforms/
COPY package-rstudio-server $SOURCE_DIR/
RUN $SOURCE_DIR/package-rstudio-server > package-rstudio-server.log 2>&1
RUN apt-get install -y $BUILD_DIR/$PACKAGE_FILE > package-test-install.log 2>&1
RUN cp $BUILD_DIR/$PACKAGE_FILE $R_PACKAGE_REPO/
