FROM "nvcr.io/nvidia/l4t-ml:r32.4.3-py3"
LABEL maintainer="M. Edward (Ed) Borasky <znmeb@znmeb.net>"

ARG ARROW_TARBALL
ARG DEBIAN_FRONTEND
ARG EDGYR_HOME
ARG EDGYR_LOGFILES
ARG JULIA_TARBALL
ARG RSTUDIO_PACKAGE_FILE
ARG PAPERSIZE
ARG PROJECT_HOME
ARG RSTUDIO_VERSION_MAJOR
ARG RSTUDIO_VERSION_MINOR
ARG RSTUDIO_VERSION_PATCH
ARG SOURCE_DIR
ARG WORKON_HOME

ENV ARROW_TARBALL=$ARROW_TARBALL
ENV DEBIAN_FRONTEND=$DEBIAN_FRONTEND
ENV EDGYR_HOME=$EDGYR_HOME
ENV EDGYR_LOGFILES=$EDGYR_LOGFILES
ENV JULIA_TARBALL=$JULIA_TARBALL
ENV RSTUDIO_PACKAGE_FILE=$RSTUDIO_PACKAGE_FILE
ENV PAPERSIZE=$PAPERSIZE
ENV PROJECT_HOME=$PROJECT_HOME
ENV RSTUDIO_VERSION_MAJOR=$RSTUDIO_VERSION_MAJOR
ENV RSTUDIO_VERSION_MINOR=$RSTUDIO_VERSION_MINOR
ENV RSTUDIO_VERSION_PATCH=$RSTUDIO_VERSION_PATCH
ENV SOURCE_DIR=$SOURCE_DIR
ENV WORKON_HOME=$WORKON_HOME

ARG RSTUDIO_BUILD_DIR=$SOURCE_DIR/rstudio/build
ENV RSTUDIO_BUILD_DIR=$SOURCE_DIR/rstudio/build
ARG ARROW_BUILD_DIR=$SOURCE_DIR/arrow/cpp/build
ENV ARROW_BUILD_DIR=$SOURCE_DIR/arrow/cpp/build

USER root
WORKDIR $SOURCE_DIR

# Apt operations
RUN apt-get update \
  && apt-get upgrade -y \
  && apt-get install -qqy --no-install-recommends \
    gnupg \
  && apt-get autoremove --purge \
  && apt-get clean

# allow fetching sources and add R Ubuntu repository
COPY sources.list.new /etc/apt/sources.list

# build and install r-base packages
RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E298A3A825C0D65DFD57CBB651716619E084DAB9
RUN apt-get update

# make and install the packages
COPY compile-r-base compile-r-recommended $SOURCE_DIR/
RUN $SOURCE_DIR/compile-r-base
RUN $SOURCE_DIR/compile-r-recommended

# prep RStudio Server - mostly download time and building boost
# see https://rstudio.com/products/rstudio/download-server/other-platforms/
COPY prep-rstudio-server $SOURCE_DIR/
RUN $SOURCE_DIR/prep-rstudio-server > prep-rstudio-server.log 2>&1

# package and install RStudio Server
# see https://rstudio.com/products/rstudio/download-server/other-platforms/
COPY package-rstudio-server $SOURCE_DIR/
RUN $SOURCE_DIR/package-rstudio-server > package-rstudio-server.log 2>&1
RUN apt-get install -y $RSTUDIO_BUILD_DIR/$RSTUDIO_PACKAGE_FILE > package-test-install.log 2>&1

# make and install Apache Arrow C++ libraries
ENV SOURCE_DIR=$SOURCE_DIR
ENV ARROW_TARBALL=$ARROW_TARBALL
COPY install-arrow-cpp $SOURCE_DIR/
RUN $SOURCE_DIR/install-arrow-cpp > $SOURCE_DIR/install-arrow-cpp.log 2>&1

# collect the packages into a repository
RUN mkdir --parents /usr/local/src/package-repo \
  && cp r-*/*.deb /usr/local/src/package-repo \
  && cp $RSTUDIO_BUILD_DIR/$RSTUDIO_PACKAGE_FILE /usr/local/src/package-repo/
