#! /bin/bash

set -e

apt-get update && apt-get install -qqy ant && apt-get clean
update-alternatives --set java /usr/lib/jvm/java-8-openjdk-arm64/jre/bin/java
ls -lAtr /etc/alternatives | grep java

echo "CMake"
mkdir --parents $SOURCE_DIR/rstudio/build/ && cd $SOURCE_DIR/rstudio/build/
cmake .. \
  -DRSTUDIO_TARGET=Server -DCMAKE_BUILD_TYPE=Release -DCPACK_GENERATOR=TGZ -DCPACK_SOURCE_GENERATOR=TGZ

echo "Installing"

# The Nano only has 4 GB of RAM. As a result, the Java builds swamp the available
# RAM and multi-job makes are problematic - they swap and the system appears
# unresponsive.
#
# So we only run two-job makes if we have less than 5 GB of RAM.
export RAM_KILOBYTES=`grep MemTotal /proc/meminfo | sed 's/^MemTotal:  *//' | sed 's/ .*$//'`
if [ $RAM_KILOBYTES -ge "5000000" ]
then
  export JOBS=`nproc`
else
  export JOBS=2
fi
echo "RAM_KILOBYTES = $RAM_KILOBYTES; 'make' will use $JOBS jobs."
/usr/bin/time make --jobs=$JOBS install
