#! /bin/bash

echo "Creating / entering source directory"
mkdir -p $SOURCE_DIR && cd $SOURCE_DIR

echo "Removing old R source directories"
rm -fr R-*

echo "Downloading $R_SOURCE_TARBALL"
curl -Ls $R_SOURCE_TARBALL | tar xzf -
export R_LATEST=`ls -1 | grep -e "^R-"`
echo "Using $R_LATEST"

echo "Configuring"
mkdir --parents build_dir
cd build_dir
../$R_LATEST/configure --with-blas --enable-R-shlib --enable-memory-profiling

echo "Compiling"
make --jobs=`nproc`
echo "Making standalone math library"
pushd src/nmath/standalone
make --jobs=`nproc`
make install
popd

echo "Checking"
make check

echo "Installing"
make install
cp ../R.conf /etc/ld.so.conf.d/
/sbin/ldconfig
cd ..
