#! /bin/bash

set -e

echo "Installing Linux dependencies"
apt-get update
apt-get upgrade -y
apt-get install -qqy --no-install-recommends \
  apt-utils \
  bash-completion \
  build-essential \
  bzip2 \
  ca-certificates \
  clang-10 \
  clang-format-10 \
  clang-tidy-10 \
  clang-tools-10 \
  cmake \
  curl \
  dpkg-dev \
  fakeroot \
  file \
  gfortran \
  git \
  git-lfs \
  gnupg \
  gzip \
  libssl-dev \
  libclang-10-dev \
  libclang-cpp10-dev \
  llvm-10-dev \
  llvm-10-runtime \
  llvm-10-tools \
  locales \
  lynx \
  openjdk-8-jdk-headless \
  pandoc \
  pandoc-citeproc \
  pandoc-citeproc-preamble \
  pandoc-data \
  pkg-config \
  python-argcomplete \
  python3-argcomplete \
  python-dev \
  python3-dev \
  python-optcomplete \
  python-pip \
  python3-pip \
  python-venv \
  python3-venv \
  python-virtualenv \
  python3-virtualenv \
  qpdf \
  sudo \
  tar \
  time \
  tree \
  tzdata \
  unzip \
  vim-nox \
  virtualenv \
  virtualenvwrapper \
  wget \
  zip
apt-get autoremove --purge -y
apt-get clean
