#! /bin/bash

set -e

apt-get install -qqy --no-install-recommends \
    clang-9 \
    clang-format-9 \
    clang-tidy-9 \
    clang-tools-9 \
    libclang-9-dev \
    llvm-9 \
    llvm-9-dev \
    llvm-9-runtime \
    llvm-9-tools \
  && apt-get autoremove --purge -y \
  && apt-get clean

cd $SOURCE_DIR
curl -Ls $ARROW_TARBALL \
  | tar xzf -
mv arrow-apache-arrow-* arrow

mkdir --parents $ARROW_BUILD_DIR
cd $ARROW_BUILD_DIR
cmake .. \
  -DPYTHON_EXECUTABLE=/usr/bin/python3 \
  -DARROW_BUILD_EXAMPLES=ON \
  -DARROW_BUILD_UTILITIES=ON \
  -DARROW_COMPUTE=ON \
  -DARROW_CSV=ON \
  -DARROW_CUDA=ON \
  -DARROW_DATASET=ON \
  -DARROW_FILESYSTEM=ON \
  -DARROW_FLIGHT=ON \
  -DARROW_GANDIVA=ON \
  -DARROW_HDFS=ON \
  -DARROW_IPC=ON \
  -DARROW_JSON=ON \
  -DARROW_PARQUET=ON \
  -DARROW_ORC=ON \
  -DARROW_PLASMA=ON \
  -DARROW_PYTHON=ON \
  -DARROW_TENSORFLOW=ON \
  -DARROW_WITH_BROTLI=ON \
  -DARROW_WITH_BZ2=ON \
  -DARROW_WITH_LZ4=ON \
  -DARROW_WITH_SNAPPY=ON \
  -DARROW_WITH_ZLIB=ON \
  -DARROW_WITH_ZSTD=ON \
  -DARROW_WITH_UTF8PROC=ON \
  -DPARQUET_BUILD_EXECUTABLES=ON \
  -DPARQUET_BUILD_EXAMPLES=ON
make --jobs=`nproc`
make install
