#! /bin/bash

set -e

echo "Installing Linux dependencies"
apt-get update
apt-get upgrade -y
apt-get autoremove --purge -y
apt-get install -qqy --no-install-recommends \
  bash-completion \
  build-essential \
  bzip2 \
  ca-certificates \
  cmake \
  curl \
  openjdk-8-jdk-headless \
  file \
  gfortran \
  git \
  git-lfs \
  gzip \
  libbz2-dev \
  libcairo2-dev \
  libicu-dev \
  libgit2-dev \
  libjpeg-dev \
  libjpeg-turbo8-dev \
  liblzma-dev \
  libopenblas-dev \
  libopenmpi-dev \
  libpam0g-dev \
  libpango1.0-dev \
  libpcre2-dev \
  libpng-dev \
  libreadline-dev \
  libssh2-1-dev \
  libssl-dev \
  libtiff-dev \
  libxml2-dev \
  locales \
  lynx \
  pandoc \
  pandoc-citeproc \
  pandoc-citeproc-preamble \
  pandoc-data \
  pkg-config \
  python-argcomplete \
  python3-argcomplete \
  python-dev \
  python3-dev \
  python-optcomplete \
  python-pip \
  python3-pip \
  python-virtualenv \
  python3-virtualenv \
  qpdf \
  sudo \
  tar \
  texinfo \
  time \
  tk-dev \
  tree \
  tzdata \
  unzip \
  uuid-dev \
  vim \
  virtualenv \
  virtualenvwrapper \
  wget \
  xauth \
  xfonts-base \
  xorg-dev \
  xvfb \
  zip \
  zlib1g-dev
apt-get clean
