#! /bin/bash

echo "Pulling base images"
sudo docker pull "nvcr.io/nvidia/l4t-ml:r32.4.2-py3"
echo "Building images"
export DOCKER_REPO=znmeb
/usr/bin/time ./build-base
/usr/bin/time ./build-binaries
/usr/bin/time ./build-ml
sudo docker tag edgyr-ml $DOCKER_REPO/edgyr-ml
sudo docker images
