#! /bin/bash

# check the password
if [ ${#EDGYR_PASSWORD} -lt 12 ]
then
  echo "You need to specify a new password for the 'edgyr'"
  echo "account in the 'EDGYR_PASSWORD' environment variable."
  echo "The new 'edgyr' password must be at least 12 characters!"
  exit -20
fi

./check-image.bash edgyr-base:latest "$EDGYR_PASSWORD"
