#! /bin/bash

set -e

echo ""
echo "Installed Linux packages"
dpkg-query --list

echo ""
echo "Creating virtualenv 'tensorflow-2'"
virtualenv --system-site-packages --python=/usr/bin/python3 $WORKON_HOME/tensorflow-2
source $WORKON_HOME/tensorflow-2/bin/activate
alias make="make --jobs=`nproc`"

echo ""
echo "Installing 'TensorFlow 2'"
pip install --upgrade \
  --extra-index-url https://developer.download.nvidia.com/compute/redist/jp/v44 \
  tensorflow
echo "Installing 'tensorflow-probability'"
pip install --upgrade tensorflow-probability

echo ""
echo "Python packages in 'tensorflow-2'"
pip list
