---
title: "Guide to the `edgyr-ml` Image"
output: rmarkdown::html_vignette
bibliography: vignettes.bib
vignette: >
  %\VignetteIndexEntry{Guide to the `edgyr-ml` Image}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

The `edgyr-ml` Docker image is the main end-user component of `edgyR`. It is
based on
[Machine Learning for Jetson/L4T](https://ngc.nvidia.com/catalog/containers/nvidia:l4t-ml)
[@NVIDIA2019d].

The following table lists the main features of the image:
```{r echo=FALSE}
features <- tibble::tribble(
  ~"Packages",
  "Base OS -- L4T 18.04",
  "R 4.0.2",
  "RStudio Server 1.3.959",
  "'r-reticulate' Python3 virtualenv",
  " --- numpy 1.18.3",
  " --- SymPy 1.6.1",
  " --- matplotlib 2.1.1",
  " --- onnx 1.6.0",
  " --- pandas 1.0.3",
  " --- pycuda 2019.1.2",
  " --- scikit-learn 0.22.2",
  " --- scipy 1.4.1",
  " --- torchvision 0.6.0",
  " --- PyTorch 1.5",
  " --- TensorFlow 1.15",
  " --- JupyterLab 2.1.1",
  "R user library",
  " --- caracas",
  " --- data.table",
  " --- reticulate",
  " --- knitr/rmarkdown/tinytex",
  " --- devtools/pkgdown/shiny",
  " --- rTorch",
  " --- keras",
  " --- JupyterLab R kernel",
)
knitr::kable(features)
```

## Next: Running an `edgyR` Container

`vignette("ee-running-an-edgyr-container")`

## References
