#! /bin/bash

# check the password
if [ ${#EDGYR_PASSWORD} -lt 12 ]
then
  echo "You need to specify a new password for the 'edgyr'"
  echo "account in the 'EDGYR_PASSWORD' environment variable."
  echo "The new 'edgyr' password must be at least 12 characters!"
  exit -20
fi

# check the image
if [ "$IMAGE_NAME" != "ml" -a "$IMAGE_NAME" != "system" ]
then
  echo "The 'IMAGE_NAME' variable must equal either 'ml'"
  echo "or 'system'."
  exit -30
fi

# run L4T images only on Tegra host
if [ `uname -r | grep tegra | wc -l` -le "0" -o `uname -m` != "aarch64" ]
then
  echo "Cannot run - you need to be on an L4T / Tegra host!"
  exit -10
fi

echo "Force-removing old 'edgyr' container"
echo "You can ignore errors if it doesn't exist"
sudo docker rm -f edgyr
echo "Running image znmeb/edgyr-ml:latest"
sudo docker run --detach \
  --env EDGYR_PASSWORD="$EDGYR_PASSWORD" \
  --network host --name edgyr --hostname edgyr \
  --runtime nvidia \
  "docker.io/znmeb/edgyr-$IMAGE_NAME:latest"

sleep 5
sudo docker ps
sudo docker logs edgyr
