#! /bin/bash

set -e

cd $PROJECT_HOME
rm -fr edgyR
echo "Cloning 'https://github.com/znmeb/edgyR.git'"
git clone https://github.com/znmeb/edgyR.git
cd edgyR
echo "Checking out the 'staging' branch"
git checkout staging
echo "Installing 'devtools'"
$HOME/Installers/devtools.R
echo "Installing 'edgyR' and its suggested dependencies"
Rscript -e "devtools::install(dependencies = TRUE, quiet = TRUE)"
Rscript -e "pkgdown::build_site()"
