#! /bin/bash

set -e

# This script checks a fair amount of the 'edgyR'
# infrastructure. It takes a bit of time to run.
echo "Installing 'tidyverse'"
$HOME/Installers/tidyverse.R
echo "Installing 'devtools'"
$HOME/Installers/devtools.R

cd $PROJECT_HOME
echo "Removing old 'edgyR' repo if it exists"
rm -fr edgyR
echo "Cloning 'https://github.com/znmeb/edgyR.git'"
git clone https://github.com/znmeb/edgyR.git
cd edgyR
echo "Checking out the 'staging' branch"
git checkout staging
echo "Installing 'edgyR' and its suggested dependencies"
echo "with 'devtools::install'"
Rscript -e "devtools::install(dependencies = TRUE, quiet = TRUE)"

echo ""
echo "Testing R X11 Device"
if [ `Rscript -e "grDevices::X11()" 2>&1 | wc -l` -eq "0" ]
then
  echo "R X11 device is working!"
else
  echo "R X11 device is not working -"
  echo "starting a virtual framebuffer on 'DISPLAY=:77'"
  Xvfb ":77" -ac -screen 0 1920x1080x24 &
  export DISPLAY=":77"
fi

echo "Building the 'pkgdown' site for 'edgyR'"
Rscript -e "pkgdown::build_site()"
