#! /bin/bash

set -e

echo ""
echo "Testing R X11 Device"
if [ `Rscript -e "grDevices::X11()" 2>&1 | wc -l` -eq "0" ]
then
  echo "R X11 device is working!"
else
  echo "R X11 device is not working -"
  echo "starting a virtual framebuffer on 'DISPLAY=:77'"
  Xvfb ":77" -ac -screen 0 1920x1080x24 &
  export DISPLAY=":77"
fi

echo ""
echo "Activating 'r-reticulate' virtualenv"
source $WORKON_HOME/r-reticulate/bin/activate

echo ""
echo "Testing for Jupyter"
if [ `pip list | grep -i jupyter | wc -l` -eq "0" ]
then
  echo "Sorry - Jupyter is only on the 'edgyr-ml' image"
  echo "No Jupyter for you - exiting :-("
  exit -55
fi

cd $PROJECT_HOME
echo ""
echo "If running remotely, browse to port 8888 on this host instead of 'localhost'"
jupyter lab --no-browser --ip=0.0.0.0
