#! /bin/bash

set -e

# This script checks a fair amount of the 'edgyR'
# infrastructure. It takes a bit of time to run.

cd $PROJECT_HOME
echo "Removing old 'edgyR' repo if it exists"
rm -fr edgyR
echo "Cloning 'https://github.com/znmeb/edgyR.git'"
git clone https://github.com/znmeb/edgyR.git
cd edgyR
echo "Checking out the 'staging' branch"
git checkout staging
echo "Installing 'devtools'"
installers/devtools.R
echo "Installing 'edgyR' and its suggested dependencies"
echo "with 'devtools::install'"
Rscript -e "devtools::install(dependencies = TRUE, quiet = TRUE)"

echo "Documenting with 'devtools::document'"
Rscript -e "devtools::document()"

echo "Checking with 'devtools::check'"
Rscript -e "devtools::check()"

echo "Building the 'pkgdown' site for 'edgyR'"
Rscript -e "pkgdown::build_site()"
