#! /bin/bash

set -e

echo "Installing RStudio Server build dependencies"
apt-get update
apt-get install -qqy --no-install-recommends \
  ant \
  cmake \
  libpam0g-dev \
  libssl-dev \
  openjdk-8-jdk \
  openjdk-8-jre \
  pandoc \
  pandoc-citeproc \
  pandoc-citeproc-preamble \
  uuid-dev
update-alternatives --get-selections

rm -fr rstudio*
curl -Ls \
  https://github.com/rstudio/rstudio/tarball/v$RSTUDIO_VERSION_MAJOR.$RSTUDIO_VERSION_MINOR.$RSTUDIO_VERSION_PATCH \
  | tar xzf -
mv rstudio-rstudio-* rstudio
cd rstudio

# Non-L4t Dependencies
export PANDOC_VERSION=`pandoc --version|head -n 1|sed 's/^pandoc //'`
echo "PANDOC_VERSION=$PANDOC_VERSION"

pushd dependencies/common
echo "Installing RStudio boost from source - may take a while"
/usr/bin/time ./install-boost > $SOURCE_DIR/install-boost.log 2>&1
gzip -9 $SOURCE_DIR/install-boost.log
echo "Installing dictionaries"
./install-dictionaries > /dev/null 2>&1
echo "Installing MathJax" 
./install-mathjax > /dev/null 2>&1
echo "Copying Pandoc binaries"
mkdir -p pandoc/$PANDOC_VERSION/
cp /usr/bin/pandoc* pandoc/$PANDOC_VERSION/
popd

echo "Testing R version"
# R 4.0.0+ no longer uses the symbol 'R_Slave'. As a result, there will be an
# error compiling RStudio for R more recent than 3.6.3. So if we have a newer
# R we patch the source here.
export R_VERSION_MAJOR=`R --version | head -n 1 | sed 's/^R version //' | sed 's/\..*$//'`
echo "R_VERSION_MAJOR = $R_VERSION_MAJOR"
if [ $R_VERSION_MAJOR -gt "3" ]
then
  echo "Patching RStudio source"
  sed --in-place=.bak --expression='s/R_Slave/R_NoEcho/g' $SOURCE_DIR/rstudio/src/cpp/r/session/REmbeddedPosix.cpp
fi

echo "CMake"
mkdir --parents $SOURCE_DIR/rstudio/build/ && cd $SOURCE_DIR/rstudio/build/
cmake .. \
  -DRSTUDIO_TARGET=Server -DCMAKE_BUILD_TYPE=Release -DCPACK_GENERATOR=TGZ -DCPACK_SOURCE_GENERATOR=TGZ

echo "Installing"

# The Nano only has 4 GB of RAM. As a result, the Java builds swamp the available
# RAM and multi-job makes are problematic - they swap and the system appears
# unresponsive.
#
# So we only run multi-job makes if we have more than 5 GB of RAM.
export RAM_KILOBYTES=`grep MemTotal /proc/meminfo | sed 's/^MemTotal:  *//' | sed 's/ .*$//'`
if [ $RAM_KILOBYTES -gt "5000000" ]
then
  export JOBS=`nproc`
else
  export JOBS=1
fi
echo "RAM_KILOBYTES = $RAM_KILOBYTES; 'make' will use $JOBS jobs."
/usr/bin/time make --jobs=$JOBS install

echo "Cleanup"
apt-get autoremove --purge -y \
  ant \
  cmake \
  openjdk-8-jdk \
  openjdk-8-jre
apt-get install -qqy --no-install-recommends \
  default-jdk \
  default-jre
update-alternatives --get-selections
R CMD javareconf

if [ $BUILDING_DOCKER_IMAGE == "yes" ]
then
  rm -fr rstudio
  apt-get clean
fi
