#! /bin/bash

set -e

echo "Creating virtualenv 'r-reticulate'"
virtualenv --system-site-packages --python=/usr/bin/python3 $WORKON_HOME/r-reticulate

source $WORKON_HOME/r-reticulate/bin/activate
alias make="make --jobs=`nproc`"

pip list

echo "Installing R Python interface packages"
$HOME/Installers/python-interface.R
