#! /bin/bash

set -e

echo ""
echo "Installed Linux packages"
dpkg-query --list

echo ""
echo "Creating virtualenv 'r-reticulate'"
virtualenv --system-site-packages --python=/usr/bin/python3 $WORKON_HOME/r-reticulate

source $WORKON_HOME/r-reticulate/bin/activate

alias make="make --jobs=`nproc`"

echo ""
if [ `pip list | grep -i numpy | wc -l` -gt "0" ]
then
  echo "'numpy' is already installed - won't upgrade"
else
  echo "Installing latest 'numpy'"
  pip install --upgrade numpy
fi

echo ""
echo "Installing 'SymPy'"
pip install --upgrade SymPy
echo ""
echo "Python packages in 'r-reticulate'"
pip list

echo ""
echo "Installing R Python interface packages"
$HOME/Installers/python-interface.R

echo ""
echo "Testing for Jupyter"
if [ `pip list | grep -i jupyter | wc -l` -gt "0" ]
then
  echo "Jupyter found - enabling R kernel!"
  Rscript -e "install.packages('IRkernel'); IRkernel::installspec()"
else
  echo "No Jupyter for you :-("
fi
