#! /bin/bash

set -e

apt-get update \
  && apt-get install -qqy --no-install-recommends tzdata \
  && apt-get upgrade -y \
  && apt-get install -qqy --no-install-recommends \
    apt-file \
    build-essential \
    ca-certificates \
    fakeroot \
    gnupg \
    mlocate \
    software-properties-common \
    vim-nox \
  && apt-get autoremove --purge \
  && apt-get clean
