#! /bin/bash

set -e

echo ""
echo "Creating virtualenv 'tensorflow-2'"
virtualenv --python=/usr/bin/python3 $WORKON_HOME/tensorflow-2
source $WORKON_HOME/tensorflow-2/bin/activate
alias make="make --jobs=`nproc`"

echo ""
echo "Installing 'TensorFlow 2'"
pip install --extra-index-url https://developer.download.nvidia.com/compute/redist/jp/v44 tensorflow
echo "Installing 'edward' and 'tensorflow-probability'"
pip install --upgrade edward tensorflow-probability

echo ""
echo "Python packages in 'tensorflow-2'"
pip list
