#! /bin/bash

set -e

echo ""
echo "Installed Linux packages"
dpkg-query --list

echo ""
echo "Creating fresh virtualenv 'tensorflow-2'"
rm -fr $WORKON_HOME/tensorflow-2
virtualenv --python=/usr/bin/python3 $WORKON_HOME/tensorflow-2
source $WORKON_HOME/tensorflow-2/bin/activate
alias make="/usr/bin/make --jobs=`nproc`"

echo ""
echo "Installing 'TensorFlow 2'"
/usr/bin/time pip install \
  --extra-index-url https://developer.download.nvidia.com/compute/redist/jp/v44 \
  'tensorflow > 1.99'
echo "Installing 'tensorflow-probability'"
/usr/bin/time pip install 'tensorflow-probability<0.11'

echo ""
echo "Python packages in 'tensorflow-2'"
pip list

$HOME/test-scripts/test-tensorflow-2.R
