#! /bin/bash

set -e

cd $PROJECT_HOME
rm -fr edgyR
echo "Cloning 'https://github.com/znmeb/edgyR.git'"
git clone https://github.com/znmeb/edgyR.git
cd edgyR
echo "Installing 'devtools'"
$HOME/Installers.devtools.R
echo "Installing 'edgyR' and its suggested dependencies"
Rscript -e "devtools::install(dependencies = TRUE, quiet = TRUE)"
