#! /bin/bash

set -e

echo "Testing R X11 Device"
if [ `Rscript -e "grDevices::X11()" 2>&1 | wc -l` -eq "0" ]
then
  echo "R X11 device is working!"
else
  echo "R X11 device is not working -"
  echo "starting a virtual framebuffer on 'DISPLAY=:77'"
  Xvfb ":77" -ac -screen 0 1920x1080x24 &
  export DISPLAY=":77"
fi

cd $PROJECT_HOME
rm -fr edgyR
echo "Cloning 'https://github.com/znmeb/edgyR.git'"
git clone https://github.com/znmeb/edgyR.git
cd edgyR
echo "Checking out the 'staging' branch"
git checkout staging
echo "Installing 'devtools'"
$HOME/Installers/devtools.R
echo "Installing 'edgyR' and its suggested dependencies"
Rscript -e "devtools::install(dependencies = TRUE, quiet = TRUE)"
Rscript -e "pkgdown::build_site()"
