#! /bin/bash

set -e

# build L4T images only on Tegra host
if [ `uname -r | grep tegra | wc -l` -le "0" -o `uname -m` != "aarch64" ]
then
  echo "Cannot build - you need to be on an L4T / Tegra host!"
  exit -1
fi

# check the repository definition
if [ "$DOCKER_REPO" == "" ]
then
  echo "You need to define the 'DOCKER_REPO' environment variable"
  echo "to fully tag the image to build!"
  exit -2
fi

echo "Building the image"
/usr/bin/time sudo docker build \
  --build-arg BASE_IMAGE="nvcr.io/nvidia/l4t-base:r32.4.2" \
  --tag="$DOCKER_REPO/edgyr-base:latest" \
  --file=Dockerfile.base \
.

sudo docker system prune
sudo docker images
