#! /bin/bash

set -e

function build_image () {

/usr/bin/time sudo docker build \
  --build-arg R_SOURCE_TARBALL="https://cloud.r-project.org/src/base/R-4/R-4.0.2.tar.gz" \
  --build-arg RSTUDIO_VERSION_MAJOR=1 \
  --build-arg RSTUDIO_VERSION_MINOR=3 \
  --build-arg RSTUDIO_VERSION_PATCH=959 \
  --build-arg BASE_IMAGE="$1" \
  --tag="$2" \
  --file=Dockerfile .
}

# build L4T images only on Tegra host
if [ `uname -r | grep tegra | wc -l` -gt "0" -a `uname -m` == "aarch64" ]
then
  build_image "nvcr.io/nvidia/l4t-base:r32.4.2" "$DOCKER_REPO/edgyr-jetson-base:latest"
else
  echo "Cannot build - you need to be on an L4T / Tegra host!"
fi

docker system prune
sudo docker images
