#! /bin/bash

set -e

sudo docker images

# push L4T images only from Tegra host
if [ `uname -r | grep tegra | wc -l` -le "0" -o `uname -m` != "aarch64" ]
then
  echo "Cannot push - you need to be on an L4T / Tegra host!"
  exit -1
fi

# check the repository definition
if [ "$DOCKER_REPO" == "" ]
then
  echo "You need to define the 'DOCKER_REPO' environment variable"
  echo "to fully tag the image to push!"
  exit -2
fi

sudo docker login
/usr/bin/time sudo docker push "$DOCKER_REPO/edgyr-jetson-base:latest"
