#! /bin/bash

# run L4T images only on Tegra host
if [ `uname -r | grep tegra | wc -l` -le "0" -o `uname -m` != "aarch64" ]
then
  echo "Cannot run - you need to be on an L4T / Tegra host!"
  exit -1
fi

# check the repository definition
if [ "$DOCKER_REPO" == "" ]
then
  echo "You need to define the 'DOCKER_REPO' environment variable"
  echo "to fully tag the image to run!"
  exit -2
fi

# check the password setting
if [ ${#EDGYR_PASSWORD} -lt 12 ]
then
  echo "You need to define the "EDGYR_PASSWORD" environment variable"
  echo "and the new 'edgyr' password must be at least 12 characters!"
  exit -3
fi

echo "Force-removing old 'edgyr' container"
echo "You can ignore errors if it doesn't exist"
sudo docker rm -f edgyr
echo "Running image detached"
sudo docker run --detach \
  --env EDGYR_PASSWORD=$EDGYR_PASSWORD \
  --network host --name edgyr --hostname edgyr \
  --runtime nvidia \
  "$DOCKER_REPO/edgyr-base:latest"

echo "Container startup logs"
sleep 5
sudo docker logs edgyr
