#! /usr/bin/env Rscript

print("")
print("Initializing 'tensorflow-2'")
reticulate::use_python("~/.virtualenvs/tensorflow-2/bin/python3", required = TRUE)
reticulate::use_virtualenv("tensorflow-2", required = TRUE)
print(reticulate::py_config())
print("")
print("Is 'keras' available?")
print(keras::is_keras_available())
print("")
print("Does 'caracas' work?")
library(caracas)
A <- matrix(c("x", 2, 0, "2*x"), 2, 2)
B <- as_symbol(A)
print(B)
Binv <- inv(B)
print(Binv)
tex(Binv)
print(eigen_val(Binv))
